language: node_js
matrix:
  include:
    - node_js: '8'
      script: npm run test -- --maxWorkers=2
    - node_js: '10'
      script: npm run test -- --maxWorkers=2
    - node_js: '6'
      script: npm run test -- --maxWorkers=2